version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Preparing build

  build:
    commands:
      - echo Building application

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/**/*
